Add branch naming rules and prefixes
pondigitalsolutions/guidelines-git-branching pull request #1
Opened 2023-10-10 19:30 UTC by roy-pon

Rules and prefixes added to the branching guidelines

2023-10-11 11:50 UTC, pon-james approved these changes
LGTM

2023-10-13 08:21 UTC, danielkarso-pon approved these changes

2023-10-13 08:30 UTC, zeger-pon requested changes

2023-10-13 08:30 UTC, zeger-pon commented on README.md
> +**2. Alphanumeric characters:** Use only alphanumeric characters (letters a-z, numbers 0–9) and hyphens. Avoid using punctuation, spaces, underscores, or any other non-alphanumeric characters.
I would prefer to make it even more strict, not avoid but do not use. And for fun add the regex (feature|bugfix|hotfix|docs|chore)\/[a-z0-9]+(-([a-z0-9])+)*[a-z0-9]+

2023-10-13 10:33 UTC, apiest-pon commented
Good practice starts by leading by example, why don't you use it yourself?

2023-10-13 10:38 UTC, apiest-pon approved these changes

2023-10-25 14:07 UTC, zeger-pon approved these changes

2023-10-26 07:09 UTC, pon-james approved these changes
LGTM

2023-12-05 08:32 UTC, roy-pon commented
@zeger-pon small reminder for this PR

2023-12-07 08:32 UTC, merged